version: "1.0"
services:
  api:
    build: ./api
    container_name: api_container
    ports:
      - "4000:4000"
    volumes:
      - ./api:/app
      - /app/node_modules
  myblog:
    build: ./myblog
    container_name: myblog_container
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

